name: Deploy NixOS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install deploy-rs
        run: nix profile install github:serokell/deploy-rs

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 194.242.57.139 >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to Contabo
        run: deploy .#contabo --skip-checks --remote-build

      - name: Send Telegram Success Notification
        if: success()
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          REPO_NAME=${{ github.repository }}

          # Constructing the message with Line Breaks (%0A)
          MESSAGE="🚀 *New Deployment Succeeded* %0A%0A"
          MESSAGE+="📦 *Repo:* $REPO_NAME %0A"
          MESSAGE+="🔗 *Commit:* [\`$COMMIT_HASH\`](https://github.com/$REPO_NAME/commit/$COMMIT_HASH) %0A"
          MESSAGE+="📝 *Message:* $COMMIT_MSG"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$MESSAGE" \
            -d "parse_mode=Markdown"

      - name: Send Telegram Failure Alert
        if: failure()
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          REPO_NAME=${{ github.repository }}

          MESSAGE="❌ *Deployment Failed* %0A"
          MESSAGE+="📦 *Repo:* $REPO_NAME %0A"
          MESSAGE+="⚠️ Check the logs for commit [\`$COMMIT_HASH\`](https://github.com/$REPO_NAME/actions)"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$MESSAGE" \
            -d "parse_mode=Markdown"
